#!/bin/bash
# TradingAgents-CN 手动部署脚本
# 如果自动下载失败，按此步骤手动部署

echo "=== TradingAgents-CN 手动部署指南 ==="
echo ""
echo "由于网络原因自动下载失败，请按以下步骤手动部署："
echo ""
echo "步骤1: 手动下载项目"
echo "  浏览器访问: https://github.com/hsliuping/TradingAgents-CN"
echo "  点击 Code → Download ZIP"
echo "  或使用镜像: https://ghfast.top/https://github.com/hsliuping/TradingAgents-CN/archive/refs/heads/main.zip"
echo ""
echo "步骤2: 解压到指定目录"
echo "  unzip TradingAgents-CN-main.zip -d ~/.openclaw/"
echo "  mv ~/.openclaw/TradingAgents-CN-main ~/.openclaw/TradingAgents-CN"
echo ""
echo "步骤3: 进入项目目录"
echo "  cd ~/.openclaw/TradingAgents-CN"
echo ""
echo "步骤4: 配置环境变量（可选但推荐）"
echo "  export TUSHARE_TOKEN='你的tushare_token'"
echo "  export OPENAI_API_KEY='你的openai_key'"
echo "  # 或其他LLM提供商的key"
echo ""
echo "步骤5: 启动Docker服务"
echo "  docker-compose up -d"
echo ""
echo "步骤6: 访问服务"
echo "  前端: http://localhost:3000"
echo "  后端API: http://localhost:8000"
echo "  API文档: http://localhost:8000/docs"
echo ""
echo "=== 常见问题 ==="
echo ""
echo "Q: 端口被占用？"
echo "A: 修改 docker-compose.yml 中的端口映射"
echo ""
echo "Q: 内存不足？"
echo "A: 至少需要 4GB 内存，建议 8GB"
echo ""
echo "Q: 如何更新？"
echo "A: git pull && docker-compose down && docker-compose up -d"
echo ""
echo "Q: 如何查看日志？"
echo "A: docker-compose logs -f"
echo ""
echo "Q: 数据存储在哪里？"
echo "A: MongoDB数据在 Docker volume 中，配置在 ./data/ 目录"
echo ""
echo "=== 目录结构说明 ==="
echo "  TradingAgents-CN/"
echo "  ├── docker-compose.yml     # Docker编排配置"
echo "  ├── app/                   # FastAPI后端（专有，需授权）"
echo "  ├── frontend/              # Vue3前端（专有，需授权）"
echo "  ├── agents/                # 多智能体核心代码（开源）"
echo "  ├── data/                  # 数据存储目录"
echo "  └── docs/                  # 文档"
echo ""
